Import-Module -Name .\win10setup\Modules.psm1 -Verbose

installOhMyPosh
installPSReadLine
installCascadiaNF
addEnvUserVar
monitorAndMouseOptions
wslFeatures
installWindowsTerminal
installConfigFiles
installSpotify
blockSpotifyAds
#installSpotifyTheme
#installGeniusSpotify
installUsefullApps
#installOtherApps
#installProgramAssociation
#installGpo
installVcppaio
windowsDebloat