Import-Module -Name .\win10setup\Modules.psm1 -Verbose

installOhMyPosh
installCascadiaNF
addEnvUserVar
monitorAndMouseOptions
wslFeatures
installWindowsTerminal
installConfigFiles
installSpotify
blockSpotifyAds
isntallSpotifyTheme
isntallGeniusSpotify
#installUsefullApps
installOtherApps
installProgramAssociation
installGpo
installVcppaio
windowsDebloat